### ISSUE TITLE
Documented usage doesn't match up with actual usage

### ISSUE THREAD

**Issue by trescenzi** [ewnd9/inquirer-bluebird#1]
The documentation shows usage as

`inquirer(questions).then(fn)`

when in reality, since `inquirer` is an object, usage is

`inquirer.prompt(questions).then(fn)`

**Comment by sabrehagen** [comment]
agreed, please update npm and documentation

**Comment by ewnd9** [comment]
Wow, sorry @trescenzi I somehow missed a notification (thanks @sabrehagen for reminding) and saw the issue only now. I've published `v1.0.5` with updated documentation, anything else I can improve?

**Comment by trescenzi** [comment]
No worries @ewnd9! Thanks for jumping on it when you noticed it

Everything else looks great as far as I'm concerned. It works like a charm. :smile:

**Comment by ewnd9** [comment]
Perhaps you might be interested in my other inquirer experiments:
- https://github.com/ewnd9/inquirer-question
- https://github.com/ewnd9/inquirer-credentials
- https://github.com/ewnd9/inquirer-menu

After writing the list I've realised I should have added them to the readme :smiley:

**Comment by sabrehagen** [comment]
Re what else you can improve, with your other inquirer packages you should have the console output of the prompts/flow of each example. Reading through the sample code in each `README.md` doesn't give the reader a good idea of the benefit of each library.

**Comment by ewnd9** [comment]
I've updated all the packages and added [inquirer-test](https://github.com/ewnd9/inquirer-test) for functional testing of inquirer based apps. What do you think?
